class ProductList {
  int id;
  String nameEn;
  String nameKh;
  String shopNameEn;
  String shopNameKh;
  dynamic price;
  dynamic discount;
  dynamic afterDiscount;
  String image;
  String descriptions;
  double rating;

  ProductList({
    required this.id,
    required this.nameEn,
    required this.nameKh,
    required this.shopNameEn,
    required this.shopNameKh,
    required this.price,
    required this.discount,
    required this.afterDiscount,
    required this.image,
    required this.descriptions,
    required this.rating,
  });
}

List<ProductList> productList = [
  ProductList(
    id: 101,
    nameEn: "Coffee",
    nameKh: "កាហ្វេ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 3.5,
    discount: 1,
    afterDiscount: 2.5,
    image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "The hot latte coffee",
    rating: 4.5,
  ),
  ProductList(
    id: 102,
    nameEn: "Green Tea",
    nameKh: "តែបៃតង",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 2.8,
    discount: 0.5,
    afterDiscount: 2.3,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Refreshing green tea",
    rating: 4.2,
  ),
  ProductList(
    id: 103,
    nameEn: "Black Coffee",
    nameKh: "កាហ្វេខ្មៅ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 2.0,
    discount: 0.2,
    afterDiscount: 1.8,
    image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Strong black coffee",
    rating: 4.0,
  ),
  ProductList(
    id: 104,
    nameEn: "Milk Tea",
    nameKh: "តែទឹកដោះគោ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 3.0,
    discount: 0.5,
    afterDiscount: 2.5,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Sweet milk tea",
    rating: 4.3,
  ),
  ProductList(
    id: 105,
    nameEn: "Espresso",
    nameKh: "អេស្ព្រេសសូ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 2.5,
    discount: 0.3,
    afterDiscount: 2.2,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Classic espresso shot",
    rating: 4.1,
  ),
  ProductList(
    id: 106,
    nameEn: "Cappuccino",
    nameKh: "កាពុជីណូ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 3.8,
    discount: 0.8,
    afterDiscount: 3.0,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Creamy cappuccino",
    rating: 4.6,
  ),
  ProductList(
    id: 107,
    nameEn: "Mocha",
    nameKh: "ម៉ូកា",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 4.0,
    discount: 1.0,
    afterDiscount: 3.0,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Chocolate flavored coffee",
    rating: 4.4,
  ),
  ProductList(
    id: 108,
    nameEn: "Americano",
    nameKh: "អាមេរិកាណូ",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 2.7,
    discount: 0.4,
    afterDiscount: 2.3,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Smooth americano",
    rating: 4.0,
  ),
  ProductList(
    id: 109,
    nameEn: "Iced Coffee",
    nameKh: "កាហ្វេទឹកកក",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 3.2,
    discount: 0.7,
    afterDiscount: 2.5,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Chilled iced coffee",
    rating: 4.3,
  ),
  ProductList(
    id: 110,
    nameEn: "Hot Chocolate",
    nameKh: "កាកៅរំដួល",
    shopNameEn: "Romdul",
    shopNameKh: "រំដួល",
    price: 3.6,
    discount: 0.6,
    afterDiscount: 3.0,
     image: "https://i.pinimg.com/736x/d7/cd/ec/d7cdec94bb1a046f03e1ac36fbd7b7f6.jpg",
    descriptions: "Rich hot chocolate",
    rating: 4.7,
  ),
];
